### PR TITLE
Update sys.cpp

### PR DESCRIPTION
**Pull request by Curculigo**

### CODE REVIEW

**Comment by SpartanJ** [comment]
Please provide an explanation on why this is needed. On which context?

**Comment by Curculigo** [comment]
I think you could integrate this trivial change yourself so this PR Is not necessary. I will delete it.

**Comment by SpartanJ** [comment]
The change is incorrect, i'll commit a proper fix soon.

**Comment by Curculigo** [comment]
> The change is incorrect, i'll commit a proper fix soon.

Thank you.

**Comment by SpartanJ** [comment]
[Done](https://github.com/SpartanJ/eepp/commit/d136341354f8c7c3eadf512d887fd9caac1e2d9a). This fixes the build on BSD, ecode build app script is missing though (but ecode builds just fine, you just need to run it from `bin` folder). Building from FreeBSD requires several packages (gcc, mesa GL libs, SDL2, a package called `os-generic-userland-devtools`). `CC` and `CXX` must be set in favor of gcc and g++ respectively too. I'm not familiar at all with FreeBSD so this was pretty painful.

**Comment by Curculigo** [comment]
> [Done](https://github.com/SpartanJ/eepp/commit/d136341354f8c7c3eadf512d887fd9caac1e2d9a). This fixes the build on BSD, ecode build app script is missing though (but ecode builds just fine, you just need to run it from `bin` folder). Building from FreeBSD requires several packages (gcc, mesa GL libs, SDL2, a package called `os-generic-userland-devtools`). `CC` and `CXX` must be set in favor of gcc and g++ respectively too. I'm not familiar at all with FreeBSD so this was pretty painful.

The default compiler on FreeBSD is LLVM. I don't think you need to install GCC.

**Comment by SpartanJ** [comment]
You're correct, but I used gcc because I prefer it, clang will work too. What it's absolutely needed is gmake (GNU Make), the BSD make won't work with the premake5 gmake project files.

**Comment by Curculigo** [comment]
> What it's absolutely needed is gmake (GNU Make), the BSD make won't work with the premake5 gmake project files.

Of course. BSD make is incompatible with GNU make. And you really make it annoying to build with Clang because Clang doesn't support the `-s` switch, the warnings themselves slowed down the build speed because printing to the terminal is costly. Btw, you mentioned the package `os-generic-userland-devtools`. It seems you are using GhostBSD. There is no such package on vanilla FreeBSD. I'm using vanilla FreeBSD. With your latest git code, it built out of the box on vanilla FreeBSD. The build speed is very slow, though. Because I only has 4GB of RAM. I do it only to test and I don't want to do it again. I'm still looking for your official build and nightly build.

p/s: The binary compiled on GhostBSD might not run on vanilla FreeBSD. I still suggest you to use vanilla FreeBSD. Setup is easy. You only have to follow the handbook. I'm not an expert but I can have a working after a few minutes. The binary compiled on vanilla FreeBSD will run on GhostBSD. FreeBSD is also preferred for Github CI (that I think will be used for nightly build).

**Comment by SpartanJ** [comment]
>  And you really make it annoying to build with Clang because Clang doesn't support the -s switch, the warnings themselves slowed down the build speed because printing to the terminal is costly.

Removed stripping symbols, this should have not been enabled. But it's not really costly printing a few lines into a terminal unless you're running on really old hardware.

> Btw, you mentioned the package os-generic-userland-devtools. It seems you are using GhostBSD. There is no such package on vanilla FreeBSD. I'm using vanilla FreeBSD.

I'm using both, i'll keep on FreeBSD 14.1 from now on.

> The build speed is very slow, though. Because I only has 4GB of RAM.

Yeah, I'm surprised that you can link the program with 4GB of RAM, it will take an eternity. But I can build it in under 3 minutes in a VM so I can prepare the builds until nightly builds are supported.

**Pull request closed without merging**
